title: Angry Sun
email: narfman0@gmail.com
description: >-
  Angry Sun aggregates Super Mario Brothers 3 resources. It contains
  information about strategy, videos, tips, and rom changes, mostly
  focused on RTA.
baseurl: "/angry-sun"
url: "https://narfman0.github.io"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - pages/warpless-resources.md
  - pages/links.md
  - pages/notes.md