title: Angry Sun
email: narfman0@gmail.com
description: >-
  Angry Sun aggregates Super Mario Brothers 3 resources. It contains
  information about strategy, videos, tips, and rom changes, mostly
  focused on RTA.
baseurl: ""
url: ""

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
